name: Frontend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build frontend
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2  # Update to the latest version that supports Node.js 20
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Build project
        run: |
          cd frontend
          npm run build

      # Optionally, run tests if applicable
      # - name: Run tests
      #   run: |
      #     cd frontend
      #     npm test
